### ISSUE TITLE
Useable for Postcards ?

### ISSUE THREAD

**Issue by Zwordi** [circa10a/terraform-provider-mailform#2]
Hi there,

Is it usable for there postcard services ?
If so how to load or create an valid pdf to be sent thought the api ?

Thanks,

**Comment by circa10a** [comment]
Yes, you can specify `USPS_POSTCARD` for the `service` parameter when using the `mailform_order` resource which is documented in the hashicorp registry [here](https://registry.terraform.io/providers/circa10a/mailform/latest/docs/resources/order#service). I've also updated the `mailform_pdf` resource to support converting images to pdfs in a mailform compatible format in `v0.4.2`

### Terraform example

```hcl
terraform {
  required_providers {
    mailform = {
      source = "circa10a/mailform"
    }
  }
}

provider "mailform" {
  api_token = "XXX" // If not specified, will read MAILFORM_API_TOKEN environment variable
}

// Convert image to pdf
resource "mailform_pdf" "example" {
  image_filename = "./test.jpg"
  filename       = "./test.pdf"
}

// Create mail order
resource "mailform_order" "example" {
  pdf_file       = mailform_pdf.example.filename
  service        = "USPS_POSTCARD" # For postcards
  color          = true # Likely want the postcard to be color
  message        = "Hello! This is a postcard!" # Will likely want the postcard to have a message
  to_name        = "A name"
  to_address_1   = "Address 1"
  to_city        = "Seattle"
  to_state       = "WA"
  to_postcode    = "00000"
  to_country     = "US"
  from_name      = "My name"
  from_address_1 = "My Address 1"
  from_city      = "Dallas"
  from_state     = "TX"
  from_postcode  = "00000"
  from_country   = "US"
}
```

You'll likely want to use the `color` and `message` fields for the postcard.

**Comment by circa10a** [comment]
Maybe I can update the existing `mailform_pdf` resource to support converting images 🤔

**Comment by Zwordi** [comment]
Whaou, so fast :). Thanks you will test that asap.

Thanks

27 févr. 2023 14:47:14 Caleb Lemoine ***@***.***>:

**Comment by circa10a** [comment]
Thanks @Zwordi
Did the solution work for you?

**Comment by Zwordi** [comment]
Hi,

Currently testing it. Will keep you inform.

**Comment by Zwordi** [comment]
Hi,

Currently not working on my side. Got "Error: Post "https://www.mailform.io/app/api/v1/orders": context deadline exceeded (Client.Timeout exceeded while awaiting headers)".

Went for the same block definition with variables for input. 
On my account an credit card have been added. Do I need an available credit ?

Thanks,

**Comment by circa10a** [comment]
That typically indicates you do not have connectivity to mailform. If you're not in the US, I'm not sure if mailform allows connectivity from outside of the country.

**Comment by Zwordi** [comment]
Hi,

I just tested from an VPN on Dallas and got the same output.
Same output with your example so it might be also something about my account. Any guest ?

What else could I test ? I tried with debug log without seeing anything relevant.

Thanks

**Comment by circa10a** [comment]
Hmm it feels unlikely to be the account. Have you tried different VPN tunnels?

**Comment by Zwordi** [comment]
Checked from Chicago and some results.
Tried with valid postcodes with your example but still same result.
What is your tf version ?

**Comment by circa10a** [comment]
I'm using terraform 1.3.9, but I don't think that's the issue.

For additional debugging, can you please run this from the host that you are running terraform on?

```bash
curl --verbose  --connect-timeout 10 https://www.mailform.io/app/api/v1/orders/test
```
